package com.beautyai.salon.service;

import com.beautyai.salon.model.AdCampaign;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import java.util.Map;
import java.util.UUID;

@Service
public class MetaAdService {

    @Value("${meta.ads.access-token}")
    private String accessToken;

    @Value("${meta.ads.ad-account-id}")
    private String adAccountId;

    @Value("${meta.ads.api-version}")
    private String apiVersion;

    private final RestTemplate restTemplate;
    
    // Default image hash for salon ads if not provided. (In real-life, we'd pre-upload default assets to Meta and use their hashes)
    private static final String DEFAULT_IMAGE_HASH = "mock_image_hash_001";

    public MetaAdService() {
        this.restTemplate = new RestTemplate();
    }

    /**
     * Integrates with Meta Graph API to create a campaign, ad set, and ad.
     * Returns the external Campaign ID generated by Meta.
     */
    public String createCampaign(AdCampaign campaign) {
        // If dummy token is present, we simulate a successful API call
        if ("dummy_token".equals(accessToken)) {
            System.out.println("Using Dummy Token. Simulating Meta API integration...");
            return "meta_camp_" + UUID.randomUUID().toString();
        }

        String baseUrl = "https://graph.facebook.com/" + apiVersion + "/act_" + adAccountId;
        
        try {
            // 1. Create Campaign
            String campaignId = createMetaCampaign(baseUrl, campaign.getSalonIds() + " Campaign");
            
            // 2. Create Ad Set
            String adSetId = createMetaAdSet(baseUrl, campaignId, campaign.getDailyBudget());
            
            // 3. Create Ad
            String adId = createMetaAd(baseUrl, adSetId, campaign.getSalonIds() + " Ad");
            
            return campaignId;
            
        } catch (Exception e) {
            System.err.println("Error calling Meta API: " + e.getMessage());
            throw new RuntimeException("Failed to launch campaign to Meta Ad Network", e);
        }
    }

    private String createMetaCampaign(String baseUrl, String campaignName) {
        String url = baseUrl + "/campaigns";
        
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
        
        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("name", campaignName);
        body.add("objective", "OUTCOME_TRAFFIC");
        body.add("status", "ACTIVE");
        body.add("special_ad_categories", "NONE");
        body.add("access_token", accessToken);

        HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(body, headers);
        
        ResponseEntity<Map> response = restTemplate.postForEntity(url, request, Map.class);
        return (String) response.getBody().get("id");
    }

    private String createMetaAdSet(String baseUrl, String campaignId, int dailyBudget) {
        String url = baseUrl + "/adsets";
        
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
        
        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("name", "AdSet for " + campaignId);
        body.add("campaign_id", campaignId);
        body.add("daily_budget", String.valueOf(dailyBudget * 100)); // Meta expects cents/paise
        body.add("billing_event", "IMPRESSIONS");
        body.add("optimization_goal", "LINK_CLICKS");
        body.add("bid_amount", "200");
        body.add("status", "ACTIVE");
        
        // Basic targeting config (mocked as JSON string for now)
        String targetingJson = "{\"geo_locations\": {\"countries\": [\"IN\"]}}";
        body.add("targeting", targetingJson);
        
        body.add("access_token", accessToken);

        HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(body, headers);
        
        ResponseEntity<Map> response = restTemplate.postForEntity(url, request, Map.class);
        return (String) response.getBody().get("id");
    }

    private String createMetaAd(String baseUrl, String adSetId, String adName) {
        String url = baseUrl + "/ads";
        
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
        
        MultiValueMap<String, String> body = new LinkedMultiValueMap<>();
        body.add("name", adName);
        body.add("adset_id", adSetId);
        body.add("status", "ACTIVE");
        
        // Define creative directly or reference a creative ID. We'll reference a mock creative creation step here
        // In a full implementation, you would first call /adcreatives to get a creative ID
        // For brevity, assuming we already have a creative ID or inline creative structure.
        body.add("creative", "{\"creative_id\": \"mock_creative_id_123\"}"); 
        
        body.add("access_token", accessToken);

        HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(body, headers);
        
        ResponseEntity<Map> response = restTemplate.postForEntity(url, request, Map.class);
        return (String) response.getBody().get("id");
    }
}
